library(shiny)
library(datasets)
library(ggplot2) 
library(repmis)
library(data.table)
load("data.Rda")
batters=unique(batting_data_over_100$batter_name)
bases<-data.frame(x=c(0,45/sqrt(2),0, -45/sqrt(2),0), y=c(0,45/sqrt(2),2*45/sqrt(2),45/sqrt(2),0))
